language: java
jdk: oraclejdk8
before_install:
- chmod +x gradlew
script:
- "./gradlew wrapper"
- "./gradlew clean build"
- "./gradlew warNoStatic warCopy zipGetVersion zipStatic"
deploy:
  provider: releases
  api_key:
    secure: pt+oqlygtteFS8eUfPDq8bkfoHdZXv0HNxZC2YhEg/Sw3kJ7H26zc8DaK4M9Swv6xZy1uQCnwPBh7pohNgXi8v5LjZOjCyNHw1Fl7uaAN39cMr+XTOYcaugpTup5d9sZDJ4582tgofVt4f4+CsEIQB+hFVKqsqBlL8tl0TlzU3+rZf3BbWmCbCoibMcFocDkBm+FR0gK+uUi3SBagtcRoA97qEco9c3nLbpe9fNNh7Dc4PQgRAlO3r4ruA/5V0u/uGpGVQUpvL4NcUt+PiXhPTppYTNneC4f3l6YG8RwS0XZ0ibThj2pX5utL/CdSotyx6PeFEMAgqhgb89EQKh/hL7/DYh9oAwxa98X9fG3VwMyhYXGEImuXynimQp5vw+cc6UuYzA+EKIm6+bgLcUmq2AAQE7lmuI7hxOkfTAvfW05T1Y7xTyWKZDSLkQi1waNQpu9K7G/KF1/fV82fUl2HNzFy2K3SukO/8+sKGHgiY2RXE+pf9qxTE8yZWG7KpvomEVq/eFqbWcHtBbZETQQLbmOflJ3hq3+8kgxXpvpGDMmuvr8fAZ56NJA8f4Z2hQ5KjU+NOsjGhsE9VyEGUYJkJAkVoh3QWERIOnnoY5NLGElk5/qmU/5X/F89Ru4/okvpzEx2tt6zfkygbQJ5+X0xiDsWxwjox70NdGV1o0cSJk=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    tags: true
notifications:
  slack:
    secure: SLOh6b3+nfj59miuYYIAG1b3Ahd+ZzJ+6fDE7l1xatJIF6fjSNk1FoVJxDCoamFRP1wDJK5CU6bx3G3tjk18U23+9faLW6m/uVnYtdgP9gqEB+2UkvgcX25ZkOPHtf3OWmJ+FOt+u2OmzITwIzVMWXlSNHVynfMBs9VrNIUkS0yp4IEJ040RgGyX6aVH49cURX0mVwjKy96QK6iC+YOeeZbtRP8RST3yphHQMwRcSBAITPNPDsWkyqokYyxAqxDmD3equGyX73xfWDiwnmlpsCxZDLqX0K0SHazK1mkJw6JVSfGqFUO80GswxOa1kXWgz8XAa7o5kcg5JdaFgSaPwSAmKw4kzGr5K3INLIdU+v7oGdJXsl6dPIYGp09U4enegz4o6RXTu3TA1s9jCm3spyUpDzEv5e/YDocRNqzCTb2IfCPhtOz8/xj6IgHkn/n/wJz8Leyn0o7fK0+VBE8dg7MZ8dzFlWS9I2sInxci6lMKxoM7CWh0eLQZ8jkirlKpmjnKu9faYm8BA5MUwoy1j45ODFvznuHWIGcUczqQLy+hK1vxLMT2xJzNIdOyuVWu9Jv5Jt+MEP1aGtoLwGGaahQAwWqs4Zoq1VE4FNxLVi4yE2Lrk5pKjluccXDZwjNCyVNTaVR5Rf1PKI+EjukqLVfBl8PzDWqZ++286X0jLy4=
env:
  global:
    secure: pt+oqlygtteFS8eUfPDq8bkfoHdZXv0HNxZC2YhEg/Sw3kJ7H26zc8DaK4M9Swv6xZy1uQCnwPBh7pohNgXi8v5LjZOjCyNHw1Fl7uaAN39cMr+XTOYcaugpTup5d9sZDJ4582tgofVt4f4+CsEIQB+hFVKqsqBlL8tl0TlzU3+rZf3BbWmCbCoibMcFocDkBm+FR0gK+uUi3SBagtcRoA97qEco9c3nLbpe9fNNh7Dc4PQgRAlO3r4ruA/5V0u/uGpGVQUpvL4NcUt+PiXhPTppYTNneC4f3l6YG8RwS0XZ0ibThj2pX5utL/CdSotyx6PeFEMAgqhgb89EQKh/hL7/DYh9oAwxa98X9fG3VwMyhYXGEImuXynimQp5vw+cc6UuYzA+EKIm6+bgLcUmq2AAQE7lmuI7hxOkfTAvfW05T1Y7xTyWKZDSLkQi1waNQpu9K7G/KF1/fV82fUl2HNzFy2K3SukO/8+sKGHgiY2RXE+pf9qxTE8yZWG7KpvomEVq/eFqbWcHtBbZETQQLbmOflJ3hq3+8kgxXpvpGDMmuvr8fAZ56NJA8f4Z2hQ5KjU+NOsjGhsE9VyEGUYJkJAkVoh3QWERIOnnoY5NLGElk5/qmU/5X/F89Ru4/okvpzEx2tt6zfkygbQJ5+X0xiDsWxwjox70NdGV1o0cSJk=
